import Head from 'next/head'
import Banner from '../components/banner'
import styles from '../styles/Home.module.css'
import Image from 'next/image'
import Card from '../components/card'
import coffeeStores from "../data/coffee-stores.json"

export async function getStaticProps(context) {
  return {
    props: {
      coffeeStores,
    }
  }
}

export default function Home(props) {
  console.log(props);
  const handleOnBannerBtnClick = () => {
    console.log("Hi button")
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.heroImage}>
          <Image src="/static/hero-image.png" alt="coffee pots" width={700} height={400}/>
        </div>
        <Banner buttonText="Find stores nerby" handleOnClick={handleOnBannerBtnClick}/>
        {coffeeStores.map(coffeeStore => {
          return (
          // eslint-disable-next-line react/jsx-key
          <Card key={coffeeStore.id} name={coffeeStore.name} imgUrl={coffeeStore.imgUrl} href={`/coffee-store/${coffeeStore.id}`}/>
          );
        })}
      </main>
    </div>
  )
}
